# Generated by Django 6.0.6 on 2026-07-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Muallif ismi')),
                ('bio', models.TextField(verbose_name='Tarjimai hol')),
                ('tugilgan_sana', models.DateField(verbose_name="Tug'ilgan sana")),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Yozuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200, verbose_name='Yozuv sarlavhasi')),
                ('matn', models.TextField(verbose_name='Yozuv matni')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('kayfiyat_vaqti', models.TimeField(verbose_name='Kayfiyat vaqti')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yozuvlar.muallif', verbose_name='Muallifi')),
            ],
            options={
                'verbose_name': 'Yozuv',
                'verbose_name_plural': 'Yozuvlar',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
    ]
